# Generated by Django 6.1.1 on 2026-10-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('terreno', 'Terreno'), ('local', 'Local')], max_length=20)),
                ('operacion', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], max_length=10)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='USD', max_length=3)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('zona', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('ambientes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metros_cuadrados', models.PositiveIntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='propiedades/')),
                ('disponible', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'propiedades',
                'ordering': ['-creada'],
            },
        ),
    ]
