# Generated by Django 6.1.1 on 2026-10-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/galeria/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
